[package]
name = "banana_exe_afkclicker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = "0.5.3"
winapi = { version = "0.3.9", features = ["winuser", "psapi", "windef"] }
